// @flow

export default {
  brandColor: "#00695C",
  brandSubColor: "#3F93F5",
  brandColorActive: "#00796B",
  brandSecond: "#F2F1F1",
  brandSecondActive: "#C3CBD2",
  statusBar: "#333",
  navBarHeaderColor: "#ECF2F6",
  headerHeight: 80,
  brandGreen: "#388E3C",
  brandRed: "#E4504C",
  brandYellow: "#FBEF6A",
  sidebarBackground: "#90A4AE",
  sidebarItemBackground: "#CFD7DD",
  sidebarLinkIconColor: "#00897B",
  sidebarLinkTextColor: "#555",
  disabledBackground: "#afafaf",
  listGapColor: "#ECF2F6",
  emptyMessageColor: "#BFBFBF",
  button: {
    backgroundColor: "#00adf5", /////////////////////
    inActiveBackgroundColor: "#FFF",
    topTabButtonBackgroundColor: "#ffc425",
    color: "#FFF",
    inActiveColor: "#00ff00",
    underlayColor: "#4891ff",
    transparentUnderlayColor: "#ffffff",
    dangerBGColor: "#00b159",
    borderRadius: 50,
    padding: 10,
  },
  form: {
    inputFontSize: 15,
    inputFontSizeSmall: 13,
    searchInputBackgroundColor: "#FFF",
  },
  text: {
    xBigTitleSize: 22,
    bigTitleSize: 19,
    titleSize: 17,
    buttonTextSize: 16,
    subTitleSize: 14,
    smallText: 13,
    tooSmallText: 12,
    errorTextColor: "#e85353",
    headerTextColor: "#535B69",
    fabIconColor: "#FFF",
    textColor: "#535B69",
    inputTextColor: "#000000",
    subTextColor: "#5E5E5E",
    liteText: "#EDE7F6",
    topTabText: "#AAA",
    redText: "#FF0000",
    greenText: "#3cb878",
    greyText: "#C0C0C0",
    pinkText: "#F653A6",
    iconTextColor: "#2DD1AC",
  },
  border: {
    defaultBorderColor: "#9B9B9B",
    errorBorderColor: "#ef5350",
    inputBorderColor: "#000000",
  },
  componentBackground: {
    default: "#FFF",
    footer: "#DDD",
    listItem: "#FAFAFA",
    inputBackground: "#FFF",
    labelBackground: "#FE7496",
    switchTintColor: "#CCC",
    switchOnTintColor: "#4DB6AC",
  },
  tabScreenSize: {
    minTabScreenSize: 2000,
  },
  mobileWidth: {
    maxMobileWidth: 480,
  },
  label: {
    default: "#C3CBD2",
    purpleLabel: "#E0B0FF",
    pinkLabel: "#FFC0CB",
    blueLabel: "#00BFFF",
    greyLabel: "#C0C0C0",
    redLabel: "#FF0000",
  },
};
