export const SET_STATE = "SET_STATE";
export const CLEAR_STATE = "CLEAR_STATE";
export const CLEAR_APP_STATE = "CLEAR_APP_STATE";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const ROOT_CHANGED = "ROOT_CHANGED";
export const SCREEN_CHANGE = "SCREEN_CHANGE";
export const CHANGE_FORM_LOCALE = "CHANGE_FORM_LOCALE";
export const FETCH_SCREEN_CHANGE = "FETCH_SCREEN_CHANGE";
export const REMOVE_STATE = "REMOVE_STATE";
export const CLEAN_STATE = "CLEAN_STATE";
export const ADD_TOAST = 'ADD_TOAST';

//form action types
export const ON_FIELD_CHANGE = "ON_FIELD_CHANGE";
export const RESET_FORMS = "RESET_FORMS";
export const RESET_FORM = "RESET_FORM";
export const EDIT_FORM = "EDIT_FORM";
export const SET_FORM_FIELDS = "SET_FORM_FIELDS";
export const SET_UPDATE_FORM_FIELDS = "SET_UPDATE_FORM_FIELDS";
export const UPDATE_FORM_FIELDS = "UPDATE_FORM_FIELDS";
export const RESET_UPDATE_FORM_FIELDS = "RESET_UPDATE_FORM_FIELDS";
export const POST = "POST";
export const GET = "GET";
export const PUT = "PUT";
export const DELETE = "DELETE";

// settings action types
export const CHANGE_APP_LOCALE = "CHANGE_APP_LOCALE";

export const GET_APP_LOCALE = "GET_APP_LOCALE";
export const RECEIVE_APP_LOCALE = "RECEIVE_APP_LOCALE";
export const CHANGE_LOCATION = "CHANGE_LOCATION";
export const RECEIVE_CHANGED_LOCATION = "RECEIVE_CHANGED_LOCATION";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const SET_LOCATION_NAMES = "SET_LOCATION_NAMES";
export const GET_SELECTED_LOCATION = "GET_SELECTED_LOCATION";
export const RECEIVE_SELECTED_LOCATION = "RECEIVE_SELECTED_LOCATION";
export const RECEIVE_LOCATIONS = "RECEIVE_LOCATIONS";

// AsyncStorage keys
export const SESSION = "EGN_USER_SESSION";
export const TOKEN = "EGN_TOKEN";
export const CURRENT_LOCATION = "CURRENT_LOCATION_CODE";
export const LANGUAGE = "EGN_LANG";
export const PROFILE = "PROFILE";
export const COUNTRIES = "COUNTRIES";
export const POST_OFFICES = "POST_OFFICES";
export const POLICE_STATIONS = "POLICE_STATIONS";
export const PIN = "@offline_login";
export const FIRST = "FIRST_TIME_USER"
export const HAS_PREVIOUSLY_SETUP = "HAS_PREVIOUSLY_SETUP"
export const SESSION_HANDLING = "SESSION_HANDLING";
export const HANDLE_GET_STARTED = "HANDLE_GET_STARTED";

// User action types
export const VERIFIED_USER = "VERIFIED_USER";
export const USER_SIGNUP_DATA = "USER_SIGNUP_DATA";
export const SAVE_USER = "SAVE_USER";
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
export const UPDATE_USER = "UPDATE_USER";
export const GET_SUBSCRIBED_USERS = "GET_SUBSCRIBED_USERS";
export const RECEIVE_SUBSCRIBED_USERS_BY_PROPERTY = "RECEIVE_SUBSCRIBED_USERS_BY_PROPERTY";
export const APPROVE_PROPERTY_SUBSCRIBERS = "APPROVE_PROPERTY_SUBSCRIBERS";

// Current action types
export const GET_CURRENT_COMPLAINS = "GET_CURRENT_COMPLAINS";
export const FETCH_CURRENT_COMPLAINS = "FETCH_CURRENT_COMPLAINS";
export const SAVE_CURRENT_COMPLAIN = "SAVE_CURRENT_COMPLAIN";
export const FETCH_SAVED_CURRENT_COMPLAIN = "FETCH_SAVED_CURRENT_COMPLAIN";
export const GET_CURRENT_COMPLAIN_BY_ID = "GET_CURRENT_COMPLAIN_BY_ID";
export const RECEIVE_UPDATED_CURRENT_COMPLAIN = "RECEIVE_UPDATED_CURRENT_COMPLAIN";
export const UPDATE_CURRENT_COMPLAIN = "UPDATE_CURRENT_COMPLAIN";
export const REMOVE_UPDATED_CURRENT_COMPLAIN = "REMOVE_UPDATED_CURRENT_COMPLAIN";

// Pending action types
export const GET_PENDING_COMPLAINS = "GET_PENDING_COMPLAINS";
export const FETCH_PENDING_COMPLAINS = "FETCH_PENDING_COMPLAINS";
export const SAVE_PENDING_COMPLAIN = "SAVE_PENDING_COMPLAIN";
export const FETCH_SAVED_PENDING_COMPLAIN = "FETCH_SAVED_PENDING_COMPLAIN";
export const GET_PENDING_COMPLAIN_BY_ID = "GET_PENDING_COMPLAIN_BY_ID";
export const RECEIVE_UPDATED_PENDING_COMPLAIN = "RECEIVE_UPDATED_PENDING_COMPLAIN";
export const UPDATE_PENDING_COMPLAIN = "UPDATE_PENDING_COMPLAIN";
export const REMOVE_UPDATED_PENDING_COMPLAIN = "REMOVE_UPDATED_PENDING_COMPLAIN";

// Complain action types
export const GET_COMPLAINS = "GET_COMPLAINS";
export const GET_ALL_COMPLAINS = "GET_ALL_COMPLAINS";
export const FETCH_COMPLAINS = "FETCH_COMPLAINS";
export const GET_COMPLAINT_BY_ID = "GET_COMPLAINT_BY_ID";
export const SAVE_COMPLAIN = "SAVE_COMPLAIN";
export const FETCH_SAVED_COMPLAIN = "FETCH_SAVED_COMPLAIN";
export const GET_COMPLAIN_BY_ID_FOR_NOTIFICATION = "GET_COMPLAIN_BY_ID_FOR_NOTIFICATION";
export const RECEIVE_UPDATED_COMPLAIN = "RECEIVE_UPDATED_COMPLAIN";
export const UPDATE_COMPLAIN = "UPDATE_COMPLAIN";
export const REMOVE_UPDATED_COMPLAIN = "REMOVE_UPDATED_COMPLAIN";
export const DELETE_COMPLAIN = "DELETE_COMPLAIN";
export const REMOVE__COMPLAIN = "REMOVE__COMPLAIN";

export const CLEAR_COMPLAINS = "CLEAR_COMPLAINS";
export const GET_ALL_COMPLAINT_COUNTS = "GET_ALL_COMPLAINT_COUNTS";

// Property action types
export const GET_USER_PROPERTIES = "GET_USER_PROPERTIES";
export const RECEIVE_PROPERTIES = "RECEIVE_PROPERTIES";
export const SAVE_PROPERTY = "SAVE_PROPERTY";
export const RECEIVE_SAVED_PROPERTY = "RECEIVE_SAVED_PROPERTY";
export const RECEIVE_UPDATED_PROPERTY = "RECEIVE_UPDATED_PROPERTY";
export const REMOVE_PROPERTY = "REMOVE_PROPERTY";
export const RECEIVE_REMOVED_PROPERTY = "RECEIVE_REMOVED_PROPERTY";
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";

// Completed action types
export const GET_COMPLETED_COMPLAINS = "GET_COMPLETED_COMPLAINS";
export const RECEIVE_UPDATED_COMPLETED_COMPLAIN = "RECEIVE_UPDATED_COMPLETED_COMPLAIN";
export const UPDATE_COMPLETED_COMPLAIN = "UPDATE_COMPLETED_COMPLAIN";
export const REMOVE_UPDATED_COMPLETED_COMPLAIN = "REMOVE_UPDATED_COMPLETED_COMPLAIN";
export const FETCH_COMPLETED_COMPLAINS = "FETCH_COMPLETED_COMPLAINS";
export const DELETE_COMPLETED_COMPLAIN = "DELETE_COMPLETED_COMPLAIN";
export const GET_COMPLAIN_COMMENTS = "GET_COMPLAIN_COMMENTS";
export const RECEIVE_COMPLAIN_COMMENTS = "RECEIVE_COMPLAIN_COMMENTS";
export const RECEIVE_SAVED_COMPLAIN_COMMENT = "RECEIVE_SAVED_COMPLAIN_COMMENT";
export const SAVE_COMPLAIN_COMMENT = "SAVE_COMPLAIN_COMMENT";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";
export const GET_COMPLAIN_HISTORY = "GET_COMPLAIN_HISTORY";
export const RECEIVE_COMPLAIN_HISTORY = "RECEIVE_COMPLAIN_HISTORY";
export const CLEAR_COMPLAIN_HISTORY = "CLEAR_COMPLAIN_HISTORY";

//user action types
export const AUTH_USER = "AUTH_USER";
export const RECEIVE_PROFILE = "RECEIVE_PROFILE";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const CHANGE_INITIAL_PASSWORD = "CHANGE_INITIAL_PASSWORD";
export const GET_PROFILE = "GET_PROFILE";
export const CHECK_LAST_ONLINE_TIME = "CHECK_LAST_ONLINE_TIME";
export const SET_USER_FORCE_LOGOUT = "SET_USER_FORCE_LOGOUT";
export const FORCE_USER_TO_LOGOUT = "FORCE_USER_TO_LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const VERIFY_PIN = "VERIFY_PIN";
export const RESEND_PIN = "RESEND_PIN";
export const RECEIVE_UPDATED_SUBSCRIBED_USER = "RECEIVE_UPDATED_SUBSCRIBED_USER";
export const UPDATE_USER_DEVICE_ID = "UPDATE_USER_DEVICE_ID";
export const INVITE_USER_TO_PROPERTY = "INVITE_USER_TO_PROPERTY";
export const RECEIVE_INVITED_USERS = "RECEIVE_INVITED_USERS";
export const CLEAR_INVITED_USERS = "CLEAR_INVITED_USERS";
export const INVITE_USER = "INVITE_USER";
export const GET_CURRENT_ADMINS = "GET_CURRENT_ADMINS";
export const RECEIVE_CURRENT_ADMINS = "RECEIVE_CURRENT_ADMINS";
export const GET_ALL_ADMINS = "GET_ALL_ADMINS";
export const RECEIVE_ALL_ADMINS = "RECEIVE_ALL_ADMINS";
export const MAKE_ADMIN = "MAKE_ADMIN";
export const REMOVE_FROM_ADMIN = "REMOVE_FROM_ADMIN";
export const REMOVE_FROM_ALL_ADMINS = "REMOVE_FROM_ALL_ADMINS";
export const ADD_TO_ALL_ADMINS = "ADD_TO_ALL_ADMINS";
export const ADD_TO_CURRENT_ADMINS = "ADD_TO_CURRENT_ADMINS";
export const REMOVE_FROM_CURRENT_ADMINS = "REMOVE_FROM_CURRENT_ADMINS";
export const REMOVE_COMPLAINERS = "REMOVE_COMPLAINERS";

export const GET_COMPLAINERS = "GET_COMPLAINERS";
export const RECEIVE_COMPLAINERS = "RECEIVE_COMPLAINERS";
export const GET_SUGGESTED_COMPLAINERS = "GET_SUGGESTED_COMPLAINERS";

//Listners types
export const OFFLINE_TIME_CHECK = "offlineTimeCheck";

//Row count
export const DEFAULT_NUMBER_OF_ROWS = 12;

// Transliteration
export const TRANSLITERATE = "TRANSLITERATE";

// Application language keys
export const LANG_STACK = ["en", "si", "tl"];

// Badge data
export const BADGE_DATA = {
    completed: {
        badgeType: "success",
        badgeText: 'COMPLETED',
        badgeColor: "#69C31D"
    },
    pending: {
        badgeType: "success",
        badgeText: 'PENDING',
        badgeColor: "#FFA726"
    },
    inProgress: {
        badgeType: "success",
        badgeText: 'IN PROGRESS',
        badgeColor: "#FACF10"
    },
    reOpen: {
        badgeType: "success",
        badgeText: 'RE OPEN',
        badgeColor: "#20C7EF"
    },
    onHold: {
        badgeType: "success",
        badgeText: 'ON HOLD',
        badgeColor: "#D57350"
    }
}

//Complain Type action types
export const GET_COMPLAIN_TYPES = "GET_COMPLAIN_TYPES";
export const FETCH_COMPLAIN_TYPES = "FETCH_COMPLAIN_TYPES";
export const SAVE_COMPLAIN_TYPE = "SAVE_COMPLAIN_TYPE";
export const FETCH_SAVED_COMPLAIN_TYPE = "FETCH_SAVED_COMPLAIN_TYPE";
export const GET_COMPLAIN_TYPE_BY_ID = "GET_COMPLAIN_TYPE_BY_ID";
export const RECEIVE_UPDATED_COMPLAIN_TYPE = "RECEIVE_UPDATED_COMPLAIN_TYPE";
export const UPDATE_COMPLAIN_TYPE = "UPDATE_COMPLAIN_TYPE";
export const REMOVE_COMPLAIN_TYPE = "REMOVE_COMPLAIN_TYPE";
export const UPDATE_REMOVED_COMPLAIN_TYPE = "UPDATE_REMOVED_COMPLAIN_TYPE";
export const CLEAR_COMPLAIN_TYPES = "CLEAR_COMPLAIN_TYPES";

//Notifications action types
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const RECEIVE_NOTIFICATIONS = "RECEIVE_NOTIFICATIONS";
export const GET_NOTIFICATION_COMPLAIN_DETAILS_BY_ID = "GET_NOTIFICATION_COMPLAIN_DETAILS_BY_ID";
export const READ_NOTIFICATION = "READ_NOTIFICATION";
export const NOTIFICATION_NOTIFIED = "NOTIFICATION_NOTIFIED";
export const RECEIVE_READ_NOTIFICATION = "RECEIVE_READ_NOTIFICATION";
export const CLEAR_CURRENT_ADMINS = "CLEAR_CURRENT_ADMINS";
export const NOTIFICATION_COUNT = "NOTIFICATION_COUNT";
export const NOTIFICATION_COUNT_NOTIFIED = "NOTIFICATION_COUNT_NOTIFIED";

//changePassword
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const GET_HOST_ENVIRONMENT = "GET_HOST_ENVIRONMENT";
export const HOSTED_ENVIRONMENT = "HOSTED_ENVIRONMENT";
export const UNIQUE_SIGNALR_DEVICE_ID = "UNIQUE_SIGNALR_DEVICE_ID";
export const GENERATE_UNIQUE_ID = "GENERATE_UNIQUE_ID";
export const APPLY_FILTERS = "APPLY_FILTERS";
export const SET_FILTERS = "SET_FILTERS";
export const REMOVE_FILTERS = "REMOVE_FILTERS";

export const GET_ALL_COMPLAINERS = "GET_ALL_COMPLAINERS";
export const RECEIVE_ALL_COMPLAINERS = "RECEIVE_ALL_COMPLAINERS";

export const GET_COMPLAIN_COUNT_BY_USERS = "GET_COMPLAIN_COUNT_BY_USERS";
export const ON_CHART_FIELD_CHANGE = "ON_CHART_FIELD_CHANGE";
export const RECEIVE_COMPLAIN_COUNT_BY_USERS = "RECEIVE_COMPLAIN_COUNT_BY_USERS";

export const GET_COMPLAIN_COUNT_BY_TYPE = "GET_COMPLAIN_COUNT_BY_TYPE";
export const RECEIVE_COMPLAIN_COUNT_BY_TYPE = "RECEIVE_COMPLAIN_COUNT_BY_TYPE";

export const GET_CHARTS_DATA = "GET_CHARTS_DATA";
export const RECEIVE_CHARTS_ALL_DATA = "RECEIVE_CHARTS_ALL_DATA";
export const RECEIVE_CHARTS_FILTERED_DATA = "RECEIVE_CHARTS_FILTERED_DATA";
export const APPLY_CHART_FILTERS = "APPLY_CHART_FILTERS";
export const SET_CHART_FILTERS = "SET_CHART_FILTERS";
export const REMOVE_CHART_FILTERS = "REMOVE_CHART_FILTERS";